FROM python:3.8.10-slim-buster

COPY . /app/

WORKDIR /app

RUN pip uninstall -y bson \
    && pip uninstall -y pymongo \
    && pip install -r requirements.txt

CMD ["uvicorn", "convert_data_for_frontend:app", "--host", "0.0.0.0", "--port", "80"]
