version: "3.8"
services:
  mongodb:
    image: "mongo:4.4.3-bionic"
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - /home/christ/Documents/git/devnet_training/automapping/storage/db:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped
  api:
    build:
      context: /home/christ/Documents/git/devnet_training/automapping/compute/
      dockerfile: Dockerfile.api
    ports: 
    - 8000:80
  #topo_scrapper:
  #  build:
  #    context: /home/christ/Documents/git/devnet_training/automapping/compute/
  #    dockerfile: Dockerfile.scrapper
  topo_scrapper_snmp:
    build:
      context: /home/christ/Documents/git/devnet_training/automapping/compute/
      dockerfile: Dockerfile.scrappersnmp
    env_file:
    - /home/christ/Documents/git/devnet_training/automapping/.snmp
  #stats_crawler:
  #  build:
  #    context: /home/christ/Documents/git/devnet_training/automapping/compute/
  #    dockerfile: Dockerfile.stats
  stats_crawler_snmp:
    build:
      context: /home/christ/Documents/git/devnet_training/automapping/compute/
      dockerfile: Dockerfile.statsnmp
    env_file:
    - /home/christ/Documents/git/devnet_training/automapping/.snmp
  apache:  
    image: "httpd:2.4"
    volumes:
    - /home/christ/Documents/git/devnet_training/automapping/frontend/public-html/:/usr/local/apache2/htdocs/
    - /home/christ/Documents/git/devnet_training/automapping/frontend/my-httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports: 
    - 8080:80
